# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Zhentao Shi
  url:        http://frankshi.github.io/GMM-Lasso

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown